import { Product } from "./Product.js";

const products = [
  { id: 1, name: "Oxford Button-Down Shirt", price: 59.99, image: "./media/Oxford-Button-Down-Shirt.jpg", description: "Classic cotton oxford for daily wear.", sizes: ["S", "M", "L", "XL"], colors: ["White", "Blue", "Charcoal"], bullets: ["Breathable cotton weave", "Regular fit", "Wrinkle-resistant finish"], category: "Clothing", featured: true },
  { id: 2, name: "Slim Chino Pants", price: 69.99, image: "./media/Slim-Chino-Pants.avif", description: "Modern chinos for office and weekend looks.", sizes: ["30", "32", "34", "36"], colors: ["Khaki", "Navy", "Olive"], bullets: ["Stretch twill fabric", "Tapered leg", "Reinforced stitching"], category: "Clothing", featured: false },
  { id: 3, name: "Crew Neck Tee 3-Pack", price: 34.99, image: "./media/Crew-Neck-Tee-3-Pack.avif", description: "Soft everyday tees in essential colors.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "White", "Gray"], bullets: ["Combed cotton", "Tagless comfort", "Easy-care fabric"], category: "Clothing", featured: true },
  { id: 4, name: "Performance Polo", price: 44.99, image: "./media/Performance-Polo.webp", description: "Lightweight polo with moisture control.", sizes: ["S", "M", "L", "XL"], colors: ["Navy", "Burgundy", "Stone"], bullets: ["Moisture-wicking", "Four-way stretch", "Anti-odor treatment"], category: "Clothing", featured: false },
  { id: 5, name: "Merino Wool Sweater", price: 89.99, image: "./media/Merino-Wool-Sweater.jpg", description: "Fine-knit sweater for smart layering.", sizes: ["S", "M", "L", "XL"], colors: ["Heather Gray", "Forest", "Navy"], bullets: ["100% merino wool", "Breathable warmth", "Ribbed cuffs and hem"], category: "Clothing", featured: true },
  { id: 6, name: "Denim Jacket", price: 79.99, image: "./media/Denim-Jacket.webp", description: "Timeless trucker jacket in durable denim.", sizes: ["S", "M", "L", "XL"], colors: ["Indigo", "Black Wash"], bullets: ["Midweight denim", "Button front closure", "Dual chest pockets"], category: "Clothing", featured: false },
  { id: 7, name: "Athletic Joggers", price: 54.99, image: "./media/Athletic-Joggers.webp", description: "Comfort joggers for gym and lounge.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Graphite", "Navy"], bullets: ["Soft brushed interior", "Zip side pockets", "Elastic ankle cuffs"], category: "Clothing", featured: false },
  { id: 8, name: "Tailored Blazer", price: 149.99, image: "./media/Tailored-Blazer.avif", description: "Sharp blazer for formal occasions.", sizes: ["38", "40", "42", "44"], colors: ["Navy", "Charcoal"], bullets: ["Structured shoulders", "Two-button closure", "Fully lined interior"], category: "Clothing", featured: true },
  { id: 9, name: "Bomber Jacket", price: 99.99, image: "./media/Bomber Jacket.jpg", description: "Lightweight bomber with clean silhouette.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Olive", "Sand"], bullets: ["Wind-resistant shell", "Rib-knit collar", "Secure inner pocket"], category: "Clothing", featured: false },
  { id: 10, name: "Linen Short Sleeve Shirt", price: 49.99, image: "./media/Linen-Short-Sleeve-Shirt.jpg", description: "Breathable linen blend for warm weather.", sizes: ["S", "M", "L", "XL"], colors: ["Sky Blue", "White", "Sage"], bullets: ["Linen-cotton blend", "Relaxed fit", "Button-front design"], category: "Clothing", featured: false },
  { id: 11, name: "Charcoal Face Wash", price: 12.99, image: "./media/Charcoal-Face-Wash.webp", description: "Daily cleanser that removes excess oil.", volumes: ["100ml", "150ml"], bullets: ["Deep-cleansing charcoal", "Non-drying formula", "Suitable for daily use"], category: "Hygiene", featured: true },
  { id: 12, name: "Hydrating Moisturizer", price: 16.99, image: "./media/Hydrating-Moisturizer.jpg", description: "Lightweight hydration for all skin types.", volumes: ["75ml", "100ml"], bullets: ["Fast-absorbing texture", "Vitamin E enriched", "Non-greasy finish"], category: "Hygiene", featured: false },
  { id: 13, name: "Beard Oil - Cedarwood", price: 14.99, image: "./media/Beard-oil.jpg", description: "Softens beard hair and conditions skin.", volumes: ["30ml", "50ml"], scents: ["Cedarwood", "Sandalwood"], bullets: ["Natural essential oils", "Reduces itch", "Matte, non-oily feel"], category: "Hygiene", featured: true },
  { id: 14, name: "Anti-Dandruff Shampoo", price: 13.99, image: "./media/Anti-Dandruff-Shampoo.avif", description: "Scalp-care shampoo for flake control.", volumes: ["250ml", "400ml"], scents: ["Fresh Mint", "Clean Citrus"], bullets: ["Balances scalp", "Fresh mint scent", "Color-safe formula"], category: "Hygiene", featured: false },
  { id: 15, name: "Refreshing Body Wash", price: 10.99, image: "./media/Refreshing-Body-Wash.jpg", description: "Clean-rinse body wash for everyday freshness.", volumes: ["250ml", "400ml"], scents: ["Citrus Burst", "Ocean Fresh"], bullets: ["Sulfate-free cleanser", "Long-lasting scent", "Quick-rinse lather"], category: "Hygiene", featured: false },
  { id: 16, name: "Deodorant Stick - Sport", price: 8.99, image: "./media/Deodorant-Stick-Sport.webp", description: "All-day odor protection for active days.", scents: ["Sport", "Fresh Linen"], bullets: ["48-hour protection", "No white marks", "Aluminum-free"], category: "Hygiene", featured: true },
  { id: 17, name: "Aftershave Balm", price: 11.99, image: "./media/Aftershave-Balm.webp", description: "Soothes skin after shaving.", volumes: ["100ml"], scents: ["Cooling Menthol", "Unscented"], bullets: ["Cooling sensation", "Alcohol-free", "Calms razor burn"], category: "Hygiene", featured: false },
  { id: 18, name: "Whitening Toothpaste", price: 6.99, image: "./media/Whitening-Toothpaste.avif", description: "Daily toothpaste for cleaner, brighter teeth.", volumes: ["120g", "180g"], scents: ["Fresh Mint"], bullets: ["Fluoride protection", "Stain-lifting formula", "Fresh mint flavor"], category: "Hygiene", featured: false },
  { id: 19, name: "Leather Belt", price: 29.99, image: "./media/Leather-Belt.avif", description: "Versatile belt for formal and casual outfits.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Brown"], bullets: ["Genuine leather", "Polished buckle", "Trim-to-fit design"], category: "Accessories", featured: true },
  { id: 20, name: "Automatic Watch", price: 199.99, image: "./media/Automatic-Watch.jpg", description: "Classic timepiece with stainless steel build.", colors: ["Silver", "Black"], bullets: ["Self-winding movement", "Scratch-resistant glass", "Water resistant"], category: "Accessories", featured: true },
  { id: 21, name: "Polarized Sunglasses", price: 39.99, image: "./media/Polarized-Sunglasses.avif", description: "Everyday shades with UV protection.", colors: ["Black", "Tortoise"], bullets: ["UV400 lenses", "Lightweight frame", "Polarized glare reduction"], category: "Accessories", featured: false },
  { id: 22, name: "Canvas Backpack", price: 64.99, image: "./media/Canvas-Backpack.webp", description: "Durable daypack for commute and travel.", colors: ["Olive", "Black", "Tan"], bullets: ["Padded laptop sleeve", "Water-resistant canvas", "Multiple organizer pockets"], category: "Accessories", featured: false },
  { id: 23, name: "Leather Wallet", price: 34.99, image: "./media/Leather-Wallet.avif", description: "Slim wallet with secure card storage.", colors: ["Black", "Tan"], bullets: ["RFID-blocking layer", "Bifold design", "Premium leather finish"], category: "Accessories", featured: true },
  { id: 24, name: "Knit Beanie", price: 19.99, image: "./media/Knit-Beanie.jpg", description: "Warm beanie with soft stretch knit.", colors: ["Charcoal", "Navy", "Cream"], bullets: ["Soft acrylic yarn", "Stretch fit", "Fold-over cuff"], category: "Accessories", featured: false },
  { id: 25, name: "Training Duffle Bag", price: 72.99, image: "./media/Training-Duffle-Bag.avif", description: "Spacious gym bag with separate shoe compartment.", colors: ["Black", "Gray"], bullets: ["Ventilated shoe pocket", "Adjustable shoulder strap", "Water-resistant base"], category: "Accessories", featured: false }
];

// Export product data as Product instances so the app can use model methods everywhere.
export default Product.fromList(products);

